[tools]
pkl = "0.29.1"
node = '24'
hk = "1.18.1"

[env]
_.path = ["./node_modules/.bin"]
CODE_CMD = "code"

### Main tasks

[tasks.dev]
description = 'Starts the project in watch mode and opens the extension in VSCode'
depends = ['dev-extension', 'dev-webviews', 'start-vscode']

[tasks.check]
description = "Lint, type-check, and test the project"
depends = ['lint-fix', 'test', 'ts-check', 'docs:extractSettings']

[tasks.check-all]
description = "Lint, type-check, test, build docs, and run e2e tests"
depends = ['lint-fix', 'test', 'ts-check', 'docs:extractSettings', 'docs:build', 'e2e-tests']

#####################

[tasks."docs:extractSettings"]
run = 'bun src/extract-settings.mjs'
dir = "{{config_root}}/docs"

[tasks."docs:dev"]
alias = 'docs'
description = 'Builds the documentation'
run = 'exec node --run dev'
dir = "{{config_root}}/docs"
depends = ['docs:extractSettings', 'install']

[tasks."docs:build"]
run = 'node --run build'
dir = "{{config_root}}/docs"

[tasks."docs:preview"]
run = 'node --run preview'
dir = "{{config_root}}/docs"
depends = ['docs:build']

[tasks.install]
description = 'Installs dependencies with pnpm'
run = 'corepack enable && pnpm install'
sources = ['package.json', 'pnpm-lock.yaml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.start-vscode]
description = 'Starts VSCode with the extension loaded'
run = '$CODE_CMD --inspect-extensions=5858 --extensionDevelopmentPath={{cwd}}'
sources = ['src/**', 'package.json', 'syntaxes/**']
wait_for = ['install']

[tasks.watch-vscode]
run = 'mise watch -t start-vscode'

[tasks.start-vscode-inspect-brk]
description = 'Starts VSCode with the extension loaded. Pauses on the first line of the extension'
run = '$CODE_CMD --inspect-brk-extensions=5858 --extensionDevelopmentPath={{cwd}}'

[tasks.dev-extension]
depends = ['install']
description = 'Builds the project in watch mode'
run = 'rsbuild dev'

[tasks.dev-webviews]
description = 'Render webviews in watch mode.'
run = 'node --run dev-webviews'
depends = ['install']


[tasks.dev-reload-vscode]
description = 'Starts the project in watch mode and opens the extension in VSCode. Reload VSCode on changes'
depends = ['dev-extension', 'dev-webviews', 'watch-vscode']

[tasks.ts-check]
description = 'Type-check the project'
depends = ['install']
run = 'hk check --step tsc -a'

[tasks.biome-lint]
description = 'Lint the project with biome'
depends = ['install']
run = 'hk check --step biome -a'

[tasks.lint]
description = 'Lint the project + type-check'
depends = ['install']
run = 'hk check'

[tasks.lint-fix]
description = 'Lint the project + type-check and fix issues'
depends = ['install']
run = 'hk fix'

[tasks.test]
description = 'Run tests (with bun)'
depends = ['install']
run = 'node --run test'

[tasks.e2e-tests]
run = 'node --run e2e-tests'
depends = ['install']

[tasks.e2e-test-action]
tools = { act = 'latest' }
run = 'act push -j e2e-tests'
